### ISSUE TITLE
Labeler Action fails on every PR event

### ISSUE THREAD

**Issue by SpencerKaiser** [AmericanAirlines/Project-X#29]
### Pre-requisites

- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

### Describe the bug

Something is broken with our labeler Action

### To Reproduce

1. Make a PR
2. Check the logs for the Labeler Action

**Comment by johnkahn** [comment]
The extension for the labeler file is wrong. It needs to be `yml` instead of `yaml`
