### ISSUE TITLE
Create an API endpoint that returns a list of video objects

### ISSUE THREAD

**Issue by TevinBeckwith** [AmericanAirlines/Project-X#5]
**DEPENDENT ON** https://github.com/AmericanAirlines/Project-X/issues/2

The videos page will need to have a list of videos to display.  To do this it needs an endpoint to call that will return a list of videos.

**List Format**
- The list should be in json format
- each video object in the list should have keys for the fields found in the video table(See: https://github.com/AmericanAirlines/Project-X/issues/2)

**Key Features**
- The call should be a GET
- The API call should accept an optional list of query params for labels. Ex: "api/videos?labels=java,backend"
- If the labels param is provided then it should only return videos with ALL labels in the list
- If the labels param is not provided then it should return all videos

Test should be written for this endpoint as well.

**Comment by johnkahn** [comment]
Completed
