### ISSUE TITLE
SPIKE: Contribution Tracking

### ISSUE THREAD

**Issue by TevinBeckwith** [AmericanAirlines/Project-X#58]
### Pre-requisites

- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

### Describe the solution you'd like

We need to find a effective solution to keep track of user contributions.

Methods to investigate:
- Database Schema for storing contrabution data
- Contribution tracking utilities, endpoints, filters, queries, files.

**Comment by TevinBeckwith** [comment]
### Utilities needed for MVP
- GET API endpoint that returns current user pull request contributions
	- Needs filter logic to only show a select list of repositories (list pulled from database)
	- returns
		- title
		- url (for a link to the PR)
		- time merged (mergedAt)

- Point scoring system (probably calculated in page after filtering)
	- add total points field to the user table, and editable user fields
	- might be easier to do achievements and milestones instead and tie points to those

### Additional Utilities (non-MVP)
- cache the get api results, and add a button the page to force a fetch
  - add a lockout to the button to throttle user requests?
- add more precise point scoring parameters
- create new endpoint or modify the old one to include issue contributions as well



### Pages for MVP
- Contribution page
	- Displays these properties,
		- total points or earned achievements
		- latest contributions in a table (5? all?)
			- add basic filtering to the returned data
				- only show merged PRs
			- if not 'all' add button to show all
			- each contribution has a link to the initial object/page
			- How many points its worth (if using this method)

### Non-MVP Page improvements
- show issues as well
- add refresh button (with lockout?)
- show point calculation method (unless we want to keep it a mystery)
- improve filtering within the page
	- add other options

### Likely MVP Stories (in order)
- Basic api get endpoint returning all pull request contributions for the current user
- Build acievement display component (if using this method)
- Build PR display component
- Contribution page (filter: show only merged)

### Non-MVP Stories (no particular order)
- Add filter options to contribution page
- Cache contribution fetches
- Fetch issue contributions
- display issues on page

**Comment by johnkahn** [comment]
So for the request, it would be a GET request to get the data from our database right? So there would be a table for contributions that would have `nodeId`, `description`, `type`, `score`, and `contributedAt`.

Getting the data from github into that table is another issue, but that could be done with a CRON job that scans the user table for users that need their contributions updated. For this, there would be a new column on the user table, something like `contributionsLastCheckedAt`, and every time the CRON job runs it'll grab the users who haven't been updated in X seconds (some amount of time) and go fetch their contributions from GitHub and update that table.
