### ISSUE TITLE
Email checking when creating a new user

### ISSUE THREAD

**Issue by ntxnick** [AmericanAirlines/Project-X#59]
### Pre-requisites

- [ ] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

### Is your feature request related to a problem? Please describe.

Need to check the email of the users to make sure they are students when they first make their account (If they have a ".edu" email).

### Describe the solution you'd like

You will use
- Node fetch
- https://api.github.com/user/emails (use accessToken to get the emails of the user)
- Check if it is verified and look for a ".edu" email.
- Save the ".edu" email into the database.
- Procced with signing the user up.

**Comment by maxwell-tchiabe** [comment]
Hello, Can you assign me to this issue? Thank you very much.
